# ----------------------------------------------------------------------------
# Name     : .bash_profile
# Function : user startup-file for bash
# Origin   : created by /env/common/bin/login_files_change
#
# Note     : Please do not edit this file until you have read the
#            site policy file for dot-files: /etc/home/README
#
# ----------------------------------------------------------------------------
[ -r "$HOME/.bashrc" ] && . "$HOME/.bashrc"
# Setup of occ (Outline Curl Client)
#source /proj/epg_st_sandbox/reecaag/PCPB-14086/decode/occ-app/lib/bash_completion
#source /proj/epg_st_sandbox/reecaag/PCPB-14086/decode/occ-app/lib/occ-completion.bash
#export PATH=/proj/epg_st_sandbox/reecaag/PCPB-14086/decode/occ-app:$PATH
