# Clipboard
set -s set-clipboard on

# scrollback buffer n lines
set -g history-limit 100000                 
set-window-option -g xterm-keys on

### Add screen's like shortcut (C-A)
set-option -g prefix C-a
set-option -g prefix2 C-b
### How to send commands to nested tmux windows (C-A C-A command)
bind-key C-a send-prefix

# Make window and pane indexes start with 1
set -g base-index 1
setw -g pane-base-index 1

# Enable mouse mode (tmux 2.1 and above)
set -g mouse on

### don't rename windows automatically (Use C-A , to rename window)
set-window-option -g automatic-rename off
set-option -g allow-rename off

# Reduce time for escape sequences
set -s escape-time 0

### Colours can be defined both with RGB or with colour0 to colour255:
set -g default-terminal "screen-256color"

### Start with Bash new panes or windows
set-option -g default-shell /bin/bash

# loud or quiet?
set -g visual-activity off
set -g visual-bell off
set -g visual-silence off
setw -g monitor-activity off
set -g bell-action none

# split panes using | and -, make sure they open in the same path
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
unbind '"'
unbind %

### bind to reload config (thanks to gentoo wiki :)
unbind r
bind r source-file ~/.tmux.conf \; display-message "Configuration file reloaded."


### Change to buffer mode with prefix + space (appart from C-A [ or C-A PgUp)
bind-key Space copy-mode

### Change and Move Windows
bind-key Left previous-window                  # C-a Left and C-a Right to move to prev/next window
bind-key Right next-window
bind-key S-Left swap-window -t -1              # C-a Shift+Left or Shift+Right to move Window to left/right
bind-key S-Right swap-window -t +1
bind-key P swap-window -t -1
bind-key N swap-window -t +1                   # Also C-a N y C-a P (uppercase)
bind-key R command-prompt 'rename-window %%'   # Set the window name
bind-key C-R refresh-client

bind-key Pageup previous-window
bind-key Pagedown next-window

### Pane movement
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

### Pane resize
bind-key H resize-pane -L 5
bind-key J resize-pane -D 5
bind-key K resize-pane -U 5
bind-key L resize-pane -R 5

# For tmux 1.8+, Zoom / unZoom panel (C-A z or Vim's C-A _):
bind-key z resize-pane -Z

### Sane scrolling
set -g terminal-overrides 'xterm*:smcup@:rmcup@'

### Renumber windows automatically
set-option -g renumber-windows on
